{"fn":"main","ip":0,"op":"STRING","line":3,"stack":[]}
{"fn":"main","ip":2,"op":"STRING","line":3,"stack":["Hello, "]}
{"fn":"main","ip":4,"op":"CONCAT","line":3,"stack":["Hello, ","Ember"]}
{"fn":"main","ip":5,"op":"STRING","line":3,"stack":["Hello, Ember"]}
{"fn":"main","ip":7,"op":"CONCAT","line":3,"stack":["Hello, Ember","!"]}
{"fn":"main","ip":8,"op":"RETURN","line":3,"stack":["Hello, Ember!"]}
