#!/usr/bin/env bash
# tools/rebrand.sh — the scoped, allow-list Ember→Ingle rebrand helper (see docs/INGLE_RENAME_PLAN.md).
#
# This is deliberately NOT a blind `sed s/ember/ingle/`. Each phase replaces only an ENUMERATED set of
# literals in an ENUMERATED scope, so it structurally cannot touch the leave-alone internal set — the
# C runtime keeps its Ember identity: EmberRt, em_*(), ember_gfx_*(), the EMBER_* macros, ember_rt.h,
# libember_rt*.a, g_em, and the ```ember source-language grammar token. Only things a HUMAN sees on the
# terminal (error prefixes, banners, the User-Agent) and the source-file extension move.
#
# The tool PROPOSES edits in place; you then review `git diff` before committing. It is idempotent
# (re-running finds nothing left to change) and safe to run on a dirty tree.
#
#   tools/rebrand.sh strings   Bucket B — user-facing CLI/error/banner literals in src/** include/**
#   tools/rebrand.sh verify    grep-based leak check: no stray user-facing `emberc` left unaccounted for
#
# The delicate multi-line prose (the --help usage block, the --doctor screen, the install-dir path and
# the INGLE_STD/EMBER_STD env handling) is edited by hand, NOT here — those need a human eye, and the
# plan (§3) explicitly keeps them off the script. This tool covers the uniform, mechanical swaps.
set -euo pipefail

ROOT=$(cd "$(dirname "$0")/.." && pwd)
cd "$ROOT"

# In-place literal replacement across a fixed fileset, using perl so it is identical on macOS and Linux
# (BSD vs GNU sed differ on -i). Args: <perl-substitution>. The caller passes a full, anchored s/// so
# the intent is auditable at the call site.
apply() { perl -i -pe "$1" src/*.c include/*.h; }

phase_strings() {
    echo "rebrand: strings — user-facing CLI/error/banner literals (src/** include/**)"

    # (1) The error/diagnostic prefix, ×66 across src + include/ember_rt.h. The leading double-quote in
    #     the pattern guarantees a string LITERAL: `emberc: ` is never a C identifier, and the internal
    #     names (em_*, EmberRt, EMBER_*) never begin `"emberc: `, so this cannot reach them.
    apply 's/"emberc: /"inglec: /g'

    # (2) The LSP handshake name the editor sees in serverInfo (the quotes around it are ESCAPED —
    #     it lives inside a JSON string literal — so match the bare token, not "emberc-lsp").
    apply 's/emberc-lsp/inglec-lsp/g'

    # (3) The generated-docs footer credit.
    apply 's/emberc --emit=docs/inglec --emit=docs/g'

    # (4) The outward-facing HTTP User-Agent strings (Anthropic + the generic http client see these).
    apply 's#ember-claude/#ingle-claude/#g'
    apply 's#ember-http/#ingle-http/#g'

    echo "rebrand: strings done — now review \`git diff\`, then hand-edit what is kept off the script:"
    echo "         - main.c: the --doctor screen, --help usage block, --version line"
    echo "         - main.c/Makefile: install-dir path (~/.ingle) + INGLE_STD env (EMBER_STD back-compat)"
    echo "         - lsp.c: the \"source\":\"emberc\" diagnostic label (escaped quotes)"
    echo "         - codegen.c: the native-FFI compile-error hint"
    echo "         - cgen_c.c AND selfhost/cgen_c.em: the '// Generated by' header (fixed-point-coupled;"
    echo "           both must change together or the C-emit reproduction gate breaks)"
}

phase_verify() {
    echo "rebrand: verify — scanning for leftover user-facing Ember naming"
    local bad=0

    # These literals must be fully gone from the compiler sources after `strings` + the hand edits.
    for pat in '"emberc: ' '"emberc-lsp"' 'the Ember compiler' 'ember-claude/' 'ember-http/'; do
        if grep -rn -- "$pat" src include >/dev/null 2>&1; then
            echo "  [!!] still present: $pat"
            grep -rn -- "$pat" src include || true
            bad=1
        fi
    done

    # Advisory: any OTHER `emberc` still inside a string literal in the sources is worth a human glance
    # (it may be a comment — fine — or a missed banner line). Not a hard failure; just surfaced.
    echo "  --- advisory: remaining 'emberc' in src/** include/** (comments are expected/OK) ---"
    grep -rn 'emberc' src include || echo "  (none)"

    if [ "$bad" -eq 0 ]; then
        echo "rebrand: verify PASSED — no unaccounted user-facing Ember strings"
    else
        echo "rebrand: verify FAILED — resolve the [!!] items above"; return 1
    fi
}

case "${1:-}" in
    strings) phase_strings ;;
    verify)  phase_verify ;;
    *) echo "usage: tools/rebrand.sh {strings|verify}" >&2; exit 2 ;;
esac
