#!/usr/bin/env bash
# tools/rebrand.sh — the scoped, allow-list Ember→Ingle rebrand helper (see docs/INGLE_RENAME_PLAN.md).
#
# This is deliberately NOT a blind `sed s/ember/ingle/`. Each phase replaces only an ENUMERATED set of
# literals in an ENUMERATED scope, so it structurally cannot touch the leave-alone internal set — the
# C runtime keeps its Ember identity: EmberRt, em_*(), ember_gfx_*(), the EMBER_* macros, ember_rt.h,
# libember_rt*.a, g_em, and the ```ember source-language grammar token. Only things a HUMAN sees on the
# terminal (error prefixes, banners, the User-Agent) and the source-file extension move.
#
# The tool PROPOSES edits in place; you then review `git diff` before committing. It is idempotent
# (re-running finds nothing left to change) and safe to run on a dirty tree.
#
#   tools/rebrand.sh strings   Bucket B — user-facing CLI/error/banner literals in src/** include/**
#   tools/rebrand.sh verify    grep-based leak check: no stray user-facing `emberc` left unaccounted for
#
# The delicate multi-line prose (the --help usage block, the --doctor screen, the install-dir path and
# the INGLE_STD/EMBER_STD env handling) is edited by hand, NOT here — those need a human eye, and the
# plan (§3) explicitly keeps them off the script. This tool covers the uniform, mechanical swaps.
set -euo pipefail

ROOT=$(cd "$(dirname "$0")/.." && pwd)
cd "$ROOT"

# In-place literal replacement across a fixed fileset, using perl so it is identical on macOS and Linux
# (BSD vs GNU sed differ on -i). Args: <perl-substitution>. The caller passes a full, anchored s/// so
# the intent is auditable at the call site.
apply() { perl -i -pe "$1" src/*.c include/*.h; }

phase_strings() {
    echo "rebrand: strings — user-facing CLI/error/banner literals (src/** include/**)"

    # (1) The error/diagnostic prefix, ×66 across src + include/ember_rt.h. The leading double-quote in
    #     the pattern guarantees a string LITERAL: `emberc: ` is never a C identifier, and the internal
    #     names (em_*, EmberRt, EMBER_*) never begin `"emberc: `, so this cannot reach them.
    apply 's/"emberc: /"inglec: /g'

    # (2) The LSP handshake name the editor sees in serverInfo (the quotes around it are ESCAPED —
    #     it lives inside a JSON string literal — so match the bare token, not "emberc-lsp").
    apply 's/emberc-lsp/inglec-lsp/g'

    # (3) The generated-docs footer credit.
    apply 's/emberc --emit=docs/inglec --emit=docs/g'

    # (4) The outward-facing HTTP User-Agent strings (Anthropic + the generic http client see these).
    apply 's#ember-claude/#ingle-claude/#g'
    apply 's#ember-http/#ingle-http/#g'

    echo "rebrand: strings done — now review \`git diff\`, then hand-edit what is kept off the script:"
    echo "         - main.c: the --doctor screen, --help usage block, --version line"
    echo "         - main.c/Makefile: install-dir path (~/.ingle) + INGLE_STD env (EMBER_STD back-compat)"
    echo "         - lsp.c: the \"source\":\"emberc\" diagnostic label (escaped quotes)"
    echo "         - codegen.c: the native-FFI compile-error hint"
    echo "         - cgen_c.c AND selfhost/cgen_c.em: the '// Generated by' header (fixed-point-coupled;"
    echo "           both must change together or the C-emit reproduction gate breaks)"
}

phase_docs() {
    echo "rebrand: docs — Ember→Ingle across the prose docs (word-boundary, case-sensitive)"
    # Prose/source docs ONLY. This EXCLUDES:
    #   - docs/guide/** and docs/llms-full.txt : GENERATED from the book — regenerated by `make docs`
    #   - docs/install.sh                      : its own targeted pass (EMBER_* env vars + ~/.ember paths)
    #   - docs/INGLE_RENAME_PLAN.md            : the working plan; it intentionally discusses both names
    # Word-boundary + case sensitivity is the safety net: `\bEmber\b`/`\bemberc\b` cannot reach the
    # leave-alone C identifiers, which use non-matching case/shape — EmberRt (camelCase, no \b after
    # "Ember"), EMBER_* (uppercase), ember_rt / libember_rt / ```ember (lowercase). Ember.js (the real
    # JS framework) is protected by a negative lookahead. The `.em` extension is left for the ext phase.
    local files=(
        README.md
        docs/THE_INGLE_BOOK.md docs/INGLE_FROM_THE_INSIDE.md
        docs/language.md docs/architecture.md docs/OFI.md docs/faults.md docs/flare.md
        docs/start.md docs/http-design.md docs/sqlite.md docs/for-llms.md docs/llms.txt
        docs/index.html docs/what-is-ingle.html
        docs/_config.yml docs/CNAME docs/grammar.ebnf
    )
    local f
    for f in docs/design/*.md docs/_includes/*.html docs/_sass/color_schemes/*.scss docs/rss/*.xml; do
        [ -e "$f" ] && files+=("$f")
    done

    perl -i -pe '
        s/\bEmber\b(?!\.js)/Ingle/g;                       # the language name (Ember.js preserved)
        s/\bemberc\b/inglec/g;                             # the compiler binary
        s/ember-lang\.(org|com)/ingle-lang.$1/g;           # project domain (Karl owns ingle-lang.*)
        s{kmcnally5/ember-lang}{ingle-lang/ingle-lang}g;   # repo path — FLAG: confirm final repo name
        s/THE_EMBER_BOOK/THE_INGLE_BOOK/g;                 # renamed-file inbound links
        s/EMBER_FROM_THE_INSIDE/INGLE_FROM_THE_INSIDE/g;
        s/what-is-ember/what-is-ingle/g;
        s/ember\.png/ingle.png/g;
        s/color_scheme: ember/color_scheme: ingle/g;
        s{color_schemes/ember}{color_schemes/ingle}g;
        s/\bEMBER_(PREFIX|PROFILE|REPO|NO_MODIFY_PATH|STD)\b/INGLE_$1/g;  # installer+stdlib env vars
        s{/\.ember\b}{/.ingle}g;                                          # the ~/.ember install dir
    ' "${files[@]}"

    echo "rebrand: docs done on ${#files[@]} files. Next: hand-pass docs/install.sh, point build-guide.sh"
    echo "         at THE_INGLE_BOOK.md, then \`make docs\` to regenerate docs/guide/ + llms-full.txt."
    echo "         MARQUEE to review in your voice: README hero, THE_INGLE_BOOK title/intro,"
    echo "         index.html hero, what-is-ingle.html ('not Ember.js' positioning), llms.txt intro."
}

phase_verify() {
    echo "rebrand: verify — scanning for leftover user-facing Ember naming"
    local bad=0

    # These literals must be fully gone from the compiler sources after `strings` + the hand edits.
    for pat in '"emberc: ' '"emberc-lsp"' 'the Ember compiler' 'ember-claude/' 'ember-http/'; do
        if grep -rn -- "$pat" src include >/dev/null 2>&1; then
            echo "  [!!] still present: $pat"
            grep -rn -- "$pat" src include || true
            bad=1
        fi
    done

    # Advisory: any OTHER `emberc` still inside a string literal in the sources is worth a human glance
    # (it may be a comment — fine — or a missed banner line). Not a hard failure; just surfaced.
    echo "  --- advisory: remaining 'emberc' in src/** include/** (comments are expected/OK) ---"
    grep -rn 'emberc' src include || echo "  (none)"

    if [ "$bad" -eq 0 ]; then
        echo "rebrand: verify PASSED — no unaccounted user-facing Ember strings"
    else
        echo "rebrand: verify FAILED — resolve the [!!] items above"; return 1
    fi
}

case "${1:-}" in
    strings) phase_strings ;;
    docs)    phase_docs ;;
    verify)  phase_verify ;;
    *) echo "usage: tools/rebrand.sh {strings|docs|verify}" >&2; exit 2 ;;
esac
